### PR TITLE
fix(zb_io): preprocess resolver before parsing

### LINKED ISSUE #240: tap formula is not supported
Image

### PR DESCRIPTION
**Pull request by cachebag**
- [X] I have run all relevant linters for this PR.
- [X] I have read and will follow the contributing guidelines.

#

- [ ] AI was used in this PR to generate code, documentation, or other changes, and I have explained _how_ it was used below. I understand that if I do not adhere to disclosing AI usage, my PR can be closed, even without explanation.
- [X] I have not used AI for _any_ portion of this PR.

Regression from #203 

Our parser wasn't taking into consideration taps that use Ruby platform blocks (i.e. `on_macos do`, `on_linux do`, etc.) They weren't parseable by the regex-based parser since it couldn't see through nested `do...end` structure. I added a preprocessing pass that unwraps matching platform/arch conditionals and resolves `#{version}` interpolation before parsing. Inside bottle do blocks, all platform sub-blocks are kept unconditionally since bottles are data declarations, not conditional code.

Fixes #240.

### CODE REVIEW

File: zb_io/src/network/tap_formula.rs [hunk 1]
```diff
@@ -58,6 +58,14 @@ static REBUILD_RE: LazyLock<Regex> = LazyLock::new(|| {
...
     Regex::new(r#"([a-z0-9_]+):\s*"([0-9a-f]{64})""#).expect("BOTTLE_SHA_RE must compile")
 });
+static ON_PLATFORM_RE: LazyLock<Regex> = LazyLock::new(|| {
+    Regex::new(r#"^\s*on_(macos|linux|arm|intel)\s+do\b"#).expect("ON_PLATFORM_RE must compile")
+});
+static HW_CPU_RE: LazyLock<Regex> = LazyLock::new(|| {
+    Regex::new(r#"^\s*if\s+Hardware::CPU\.(arm|intel)\?"#).expect("HW_CPU_RE must compile")
+});
+static ELSE_LINE_RE: LazyLock<Regex> =
+    LazyLock::new(|| Regex::new(r#"^\s*else\s*(?:#.*)?$"#).expect("ELSE_LINE_RE must compile"));
```
Comment (maria-rcks) [inline zb_io/src/network/tap_formula.rs:71]: elsif?
