### PR TITLE
fix(zb_io, zb_cli): validate root/prefix paths before passing to sudo

### LINKED ISSUE #296: validate root/prefix paths before passing to sudo
`init.rs` passes `root` and `prefix` to `sudo mkdir`/`sudo chown` via `to_string_lossy()` with zero validation. Uses `Command::new` so no shell injection, but CLI args going straight to privileged operations should be sanitized -- no control characters, no `..` traversal, reasonable length.

Part of #293

### PR DESCRIPTION
**Pull request by cachebag**
- [X] I have run all relevant linters for this PR.
- [X] I have read and will follow the contributing guidelines.

#

- [ ] AI was used in this PR to generate code, documentation, or other changes, and I have explained _how_ it was used below. I understand that if I do not adhere to disclosing AI usage, my PR can be closed, even without explanation.
- [X] I have not used AI for _any_ portion of this PR.

We now call `validate_privileged_path` on root and prefix at the top of `run_init` so `mkdir`/`chown` never receives unsanitized CLI input. `validate_privileged_path` was created to reject control characters, '..' traversal, and excessive length before paths reach sudo commands. 

Closes #296

### CODE REVIEW

File: zb_io/src/path.rs [hunk 1]
```diff
@@ -0,0 +1,97 @@
...
+
+    for component in path.components() {
+        if matches!(component, Component::ParentDir) {
+            return Err(Error::InvalidArgument {
+                message: format!("path contains '..' traversal: {}", path.display()),
+            });
+        }
+    }
+
+    Ok(())
```
Comment (maria-rcks) [inline zb_io/src/path.rs:39]: this still allows paths starting with `-`, so sudo can still parse the path as an option.
please reject leading-dash paths here or add -- before every user-controlled path
