### PR TITLE
fix(zb_io): skip libexec virtualenv metadata links to avoid conflicts

### LINKED ISSUE #156: error: link conflict at ... prefix/libexec/lib64'
Hi, I encountered an issue with latest main version to install ansible-lint on debian like distro. I can live without it, but worth mentioning:

```bash
❯ zb install ansible-lint
==> Installing ansible-lint...
==> Resolving dependencies (15 packages)...
    ca-certificates 2025-12-02
    libyaml 0.2.5
    lz4 1.10.0
    mpdecimal 4.0.1
    openssl@3 3.6.1
    pycparser 3.0
    cffi 2.0.0
    cryptography 46.0.4
    readline 8.3.3
    rpds-py 0.30.0
    sqlite 3.51.2
    xz 5.8.2
    zstd 1.5.7
    python@3.14 3.14.2
    ansible-lint 26.1.1
==> Downloading and installing...
    pycparser        ✓ installed
    libyaml          ✓ installed
    rpds-py          ✓ installed
    cryptography     ✓ installed
    cffi             ✓ installed
    ansible-lint     ⠏ linking...                                                                                                                                                                                                               error: link conflict at '/home/myuser/local/share/zerobrew/prefix/libexec/lib64'
```

### PR DESCRIPTION
**Pull request by maria-rcks**
- [x] I have run all relevant linters for this PR.
- [x] I have read and will follow the contributing guidelines.

#

- [x] AI was used in this PR to generate code, documentation, or other changes, and I have explained _how_ it was used below. I understand that if I do not adhere to disclosing AI usage, my PR can be closed, even without explanation.
- [ ] I have not used AI for _any_ portion of this PR.

> AI-Assisted: test by gpt-5.3-codex, manually reviewed and tested

fixes #156

### CODE REVIEW

File: zb_io/src/cellar/link.rs [hunk 1]
```diff
@@ -462,6 +481,48 @@ mod tests {
         assert!(linked_helper.is_symlink(), "should be a symlink");
     }
 
+    #[test]
+    fn skips_libexec_virtualenv_metadata_to_avoid_conflicts() {
+        let tmp = TempDir::new().unwrap();
+        let prefix = tmp.path();
+        let linker = Linker::new(prefix).unwrap();
+
+        let keg1 = prefix.join("Cellar/ranger/1.0.0");
```
Comment (cachebag) [inline zb_io/src/cellar/link.rs]: Most tests use cellar. This still works because `keg_name_from_path` is case-insensitive, though it’s inconsistent.

File: zb_io/src/cellar/link.rs [hunk 2]
```diff
@@ -6,6 +6,15 @@ use zb_core::{ConflictedLink, Error};
 
 const LINK_DIRS: &[&str] = &["bin", "lib", "libexec", "include", "share", "etc"];
 
+fn should_skip_link_entry(src_dir: &Path, entry_name: &std::ffi::OsStr) -> bool {
+    // Homebrew-style Python virtualenv formulae commonly place metadata files at
+    // libexec/.gitignore and libexec/pyvenv.cfg. Linking these into a shared
+    // prefix/libexec causes cross-formula conflicts (e.g. ranger vs ansible-lint)
+    // even though they are not executable entrypoints users need on PATH.
+    src_dir.file_name().and_then(|n| n.to_str()) == Some("libexec")
+        && matches!(entry_name.to_str(), Some(".gitignore" | "pyvenv.cfg"))
```
Comment (cachebag) [inline zb_io/src/cellar/link.rs]: Let's make it trivial to add entries in the future if needed.

```rust
const LIBEXEC_SKIP_FILES: &[&str] = &[".gitignore", "pyvenv.cfg"];
```
