### PR TITLE
fix(zb_io): isolate HTTP/2 connections per racing download to prevent stream contention

### LINKED ISSUE #116: racing connections workaround
#51 broke macOS builds 

Instead of disabling racing (as we've done in #115), the fix should isolate or eliminate HTTP/2 stream contention e.g., by using separate TLS/HTTP clients per racing connection or forcing HTTP/1.1 for raced downloads.

### PR DESCRIPTION
**Pull request by cachebag**
Fixes #116 

Racing connections shared a single HTTP/2 connection, bad news bears. We can avoid stream contention and flow-control blocking by sharing a TLS config and creating separate `reqwest` clients per racing connection. 

This re-enables them for both macOS and linux (woo). Tested on both macOS and Linux.

I also bumped all version deps and fixed a strangling clippy issue (bb069642276f31018188d8090dc5b3c0ae74f257) that somehow wasn't caught in CI(?)

### CODE REVIEW

File: zb_io/src/download.rs [hunk 1]
```diff
@@ -75,36 +73,70 @@ struct CachedToken {
...
+
         Self {
             client: reqwest::Client::builder()
                 .user_agent("zerobrew/0.1")
                 .pool_max_idle_per_host(10)
                 .tcp_nodelay(true)
                 .tcp_keepalive(Duration::from_secs(60))
                 .connect_timeout(Duration::from_secs(30))
-                .timeout(Duration::from_secs(300)) // 5 min total request timeout
+                .timeout(Duration::from_secs(300))
```
Comment (lucasgelfond) [inline zb_io/src/download.rs:170]: sidenote, fine to merge, should we put these in a config somewhere eventually?

File: zb_io/src/download.rs [hunk 2]
```diff
@@ -75,36 +73,70 @@ struct CachedToken {
...
+            .user_agent("zerobrew/0.1")
+            .use_preconfigured_tls(self.tls_config.clone())
+            .pool_max_idle_per_host(0)
+            .tcp_nodelay(true)
+            .tcp_keepalive(Duration::from_secs(60))
+            .connect_timeout(Duration::from_secs(30))
+            .timeout(Duration::from_secs(300))
+            .http2_adaptive_window(true)
+            .http2_initial_stream_window_size(Some(2 * 1024 * 1024))
+            .http2_initial_connection_window_size(Some(4 * 1024 * 1024))
```
Comment (lucasgelfond) [inline zb_io/src/download.rs:195]: i.e. we're reusing a bunch of these args

**Review by lucasgelfond — APPROVED** [review]
some nits, but this looks good to me!

File: zb_io/src/download.rs (hunk 1 above)
Comment (cachebag) [reply zb_io/src/download.rs:170]: I'll add a TODO/FIXME. I think right now its fine, premature optimization is the root of all evil IMO

**Review by cachebag — COMMENTED** [review]
Perf gains are still to be seen, but comparing `master:HEAD` to this PR, we still see racing connections working (both on macOS and linux) which I guess was the initial goal of this PR.

Tracking to improve perf efforts -> #132
